version: 2018.2.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - master
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/jcBENCH.console/jcBENCH.console.csproj --verbosity m
build_script:
  - cmd: dotnet publish -c Release ./src/jcBENCH.console/jcBENCH.console.csproj
artifacts:
  - path: jcBENCH_{version}.zip
    name: jcBENCH
    type: zip
  