version: 2018.2.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
build:
  project: /src/jcBENCH.console/jcBENCH.console.csproj
  verbosity: minimal
after_build:
- cmd: 7z a jcBENCH.zip %APPVEYOR_BUILD_FOLDER%\src\jcBENCH.console\Release\netcoreapp2.0\publish\*.*
artifacts:
- path: ./src/jcBENCH.console/bin/Release/netcoreapp2.0/publish/jcBENCH.zip
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: QXEzBLTmKo/DOGKtKUweGfTj8IG/DltPwJk+O4om80fFlNUySA3ZC/rQfnsKNUq5
  force_update: true