version: 2018.2.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore ./src/jcBENCH.sln --verbosity m
build:
  project: /src/jcBENCH.console/jcBENCH.console.csproj
  verbosity: minimal
before_package:
- cmd: dotnet publish -c Release
after_build:
- cmd: 7z a jcBENCH.zip %APPVEYOR_BUILD_FOLDER%\src\Release\netcoreapp2.0\publish\*.*
artifacts:
- path: ./src/Release/netcoreapp2.0/publish/jcBENCH.zip
  name: jcBENCH
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: jcBENCH-$(appveyor_build_version)
  auth_token:
    secure: QXEzBLTmKo/DOGKtKUweGfTj8IG/DltPwJk+O4om80fFlNUySA3ZC/rQfnsKNUq5
  force_update: true
  on:
    branch: master