[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
md5 = "0.7.0"
sha1 = "0.10.6"
tokio = { version = "1", features = ["full"] }
benchmark_settings = { path = "../benchmark_settings" }