name: Deploy Web App to GCP App Engine

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        credentials_json: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
        
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v2
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        working_directory: 'src/jcBENCH.MVC/'
